db: db_evaluating_system
server:
  port: 9999
  servlet:
    context-path: /evaluating_system/
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  banner:
    location: banner.text
logging:
  path: ./logs
  level:
    root: info
    com.vincent.evaluating_system: debug
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: evaluating_system_secret #JWT加解密使用的密钥
  expiration: 21600 #JWT的超期限时间(60*60*6)
#  tokenHead: Bearer  #JWT负载中拿到开头

